services:
  - type: web
    name: estudiante
    runtime: docker
    plan: starter
    region: oregon
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/student-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MYSQLHOST
        value: metro.proxy.rlwy.net
      - key: MYSQLPORT
        value: 10422
      - key: MYSQLDATABASE
        value: railway
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        sync: false
      - key: PORT
        value: 8080